openapi: "3.0.1"
info:
  title: "${api_specification_name}"
  description: "${api_description}"
  version: "2021-06-29T12:15:37Z"
servers:
- url: "https://tppekr2irl.execute-api.eu-west-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/{api_specification_name}"
paths:
  /input:
    post:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
                default: "*"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
                default: "POST"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
                default: "Content-Type, x-api-key"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
        "500":
          description: "Internal server error"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
                default: "*"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
                default: "POST"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
                default: "Content-Type, x-api-key"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "aws"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/${lambda_api_function_arn}/invocations"
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'*'"
            responseTemplates:
              application/json: |
                #set($inputRoot = $input.path('$'))
                {
                  "statusCode": $inputRoot.statusCode,
                  "body": $inputRoot.body
                }
          ".*\"statusCode\":500.*":
            statusCode: "500"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'*'"
            responseTemplates:
             application/json: |
                #set($inputRoot = $input.path('$'))
                {
                  "statusCode": $inputRoot.statusCode
                }
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
    Error:
      type: "object"
      properties:
        message:
          type: "string"
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
